# Generated by Django 5.2.6 on 2025-09-24 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trigger_threshold', models.PositiveIntegerField(help_text='Percentage of budget')),
                ('notifications', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
